// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/e69fe60f2d6377ea4fae539493997b098f52cad1/react/react-global.d.ts
import React = __React;
import ReactDOM = __React.__DOM;

declare namespace __React {
    export import addons = __React.__Addons;
}