// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/a6cd92e3b7f9478617fa84bbe4ba91158c4baea3/serve-index/serve-index.d.ts
declare module 'serve-index' {
  import * as express from 'express';
  import * as fs from 'fs';

  namespace serveIndex {
    interface File {
      name: string;
      stat: fs.Stats;
    }

    interface Locals {
      directory: string;
      displayIcons: boolean;
      fileList: Array<File>;
      name: string;
      stat: fs.Stats;
      path: string;
      style: string;
      viewName: string;
    }

    type templateCallback = (error: Error, htmlString?: string) => void;

    interface Options {
      filter?: (filename: string, index: number, files: Array<File>, dir: string) => boolean;
      hidden?: boolean;
      icons?: boolean;
      stylesheet?: string;
      template?: string | ((locals: Locals, callback: templateCallback) => void);
      view?: string;
    }
  }

  function serveIndex(path: string, options?: serveIndex.Options): express.Handler;

  export = serveIndex;
}